name: "CodeQL"

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  codeql:
    name: üêõ CodeQL
    runs-on: ubuntu-24.04
    permissions:
      actions: read
      contents: read
      security-events: write

    steps:
    - name: üß∞ Checkout
      uses: actions/checkout@v6
      with:
        submodules: recursive

    - name: ‚úã Initialize CodeQL
      uses: github/codeql-action/init@v2
      with:
        languages: 'cpp'

    - name: üìú Setup ccache
      uses: hendrikmuhs/ccache-action@v1
      with:
        key: ${{ runner.os }}-analysis-build-${{ github.run_id }}
        restore-keys: ${{ runner.os }}-analysis-build
        max-size: 50M

    - name: üìú Restore CMakeCache
      uses: actions/cache@v5
      with:
        path: |
          build/CMakeCache.txt
        key: ${{ runner.os }}-analysis-build-${{ hashFiles('**/CMakeLists.txt') }}

    - name: ‚¨áÔ∏è Install dependencies
      run: |
        sudo apt update
        sudo bash dist/get_deps_debian.sh

    - name: üõ†Ô∏è Build
      run: |
        set -x
        mkdir -p build
        cd build
        CC=gcc-14 CXX=g++-14 cmake                \
          -DCMAKE_BUILD_TYPE=$BUILD_TYPE          \
          -DCMAKE_INSTALL_PREFIX="$PWD/install"   \
          -DCMAKE_C_COMPILER_LAUNCHER=ccache      \
          -DCMAKE_CXX_COMPILER_LAUNCHER=ccache    \
          -DCMAKE_C_FLAGS="-fuse-ld=lld"          \
          -DCMAKE_CXX_FLAGS="-fuse-ld=lld"        \
          -DIMHEX_PATTERNS_PULL_MASTER=ON         \
          -DIMHEX_EXCLUDE_PLUGINS="script_loader" \
          -G Ninja                                \
          ..
        ninja install

    - name: üóØÔ∏è Perform CodeQL Analysis
      uses: github/codeql-action/analyze@v2