name: Build for the web

on:
  push:
    branches: ["*"]
  pull_request:
  workflow_dispatch:

env:
  BUILD_TYPE: RelWithDebInfo

permissions:
  contents: write

jobs:

  build:
    runs-on: ubuntu-22.04
    name: ğŸŒ WebAssembly
    steps:
    - name: ğŸ§° Checkout
      uses: actions/checkout@v3
      with:
        submodules: recursive

    - name: ğŸ› ï¸ Build using docker
      run: |
        docker buildx build . -f dist/web/Dockerfile --progress=plain --build-arg 'JOBS=4' --output out
        cp dist/web/index.html out/index.html

    - name: â¬†ï¸ Upload artifacts
      uses: actions/upload-artifact@v3
      with:
        name: Web artifacts
        path: |
          out/*

    - name: ğŸŒ Deploy
      uses: JamesIves/github-pages-deploy-action@v4
      with:
        folder: out
