name: Build for the web

on:
  push:
    branches:
      - 'master'
      - 'releases/**'
  pull_request:
  workflow_dispatch:

env:
  BUILD_TYPE: Release

permissions:
  pages: write
  id-token: write
  actions: write

jobs:

  build:
    runs-on: ubuntu-22.04
    name: ğŸŒ WebAssembly
    steps:
    - name: ğŸ§° Checkout
      uses: actions/checkout@v4
      with:
        submodules: recursive
    
    - name: ğŸ“ Restore docker /cache
      uses: actions/cache@v4
      with:
        path: cache
        key: web-cmakecache-${{ hashFiles('**/CMakeLists.txt') }}
    
    - name: ğŸ³ Inject /cache into docker
      uses: reproducible-containers/buildkit-cache-dance@v2
      with:
        cache-source: cache
        cache-target: /cache

    - name: ğŸ› ï¸ Build using docker
      run: |
        docker buildx build . -f dist/web/Dockerfile --progress=plain --build-arg 'JOBS=4' --output out --target raw

    - name: ğŸ”¨ Fix permissions
      run: |
        chmod -c -R +rX "out/"

    - name: â¬†ï¸ Upload artifacts
      uses: actions/upload-pages-artifact@v2
      with:
        path: out/

      # See https://github.com/actions/cache/issues/342#issuecomment-1711054115
    - name: ğŸ—‘ï¸ Delete old cache
      continue-on-error: true
      env:
        GH_TOKEN: ${{ github.token }}
      run: |
          gh extension install actions/gh-actions-cache
          gh actions-cache delete "build-web-cache" --confirm
  

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
      
    name: ğŸ“ƒ Deploy to GitHub Pages
    runs-on: ubuntu-latest

    if: ${{ github.ref == 'refs/heads/master' && github.event.repository.fork == false }}
    needs: build

    steps:
      - name: ğŸŒ Deploy
        id: deployment
        uses: actions/deploy-pages@v2