name: Build for the web

on:
  push:
    branches: ["*"]
  pull_request:
  workflow_dispatch:

env:
  BUILD_TYPE: Release
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

permissions:
  pages: write
  id-token: write
  actions: write

jobs:

  build:
    runs-on: ubuntu-22.04
    name: ğŸŒ WebAssembly
    steps:
    - name: ğŸ§° Checkout
      uses: actions/checkout@v3
      with:
        submodules: recursive
    
    - name: ğŸ“ Restore docker /cache
      uses: iTrooz/cache@v3
      with:
        path: cache
        key: build-web-cache
        update: true
    
    - name: ğŸ³ Inject /cache into docker
      uses: reproducible-containers/buildkit-cache-dance@v2.1.2
      with:
        cache-source: cache
        cache-target: /cache

    - name: ğŸ› ï¸ Build using docker
      run: |
        docker buildx build . -f dist/web/Dockerfile --progress=plain --build-arg 'JOBS=4' --output out

    - name: ğŸ”¨ Fix permissions
      run: |
        chmod -c -R +rX "out/" | while read line; do
          echo "::warning title=Invalid file permissions automatically fixed::$line"
        done

    - name: â¬†ï¸ Upload artifacts
      uses: actions/upload-pages-artifact@v2
      with:
        path: out/

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
      
    name: ğŸ“ƒ Deploy to GitHub Pages
    runs-on: ubuntu-latest

    if: ${{ github.ref == 'refs/heads/master' && github.event.repository.fork == false }}
    needs: build

    steps:
      - name: ğŸŒ Deploy
        id: deployment
        uses: actions/deploy-pages@v2